export const ADMINS_REQUEST = "ADMINS_REQUEST";
export const ADMINS_SUCCESS = "ADMINS_SUCCESS";
export const ADMINS_FAIL = "ADMINS_FAIL";

export const SINGLE_ADMINS_REQUEST = "SINGLE_ADMINS_REQUEST";
export const SINGLE_ADMINS_SUCCESS = "SINGLE_ADMINS_SUCCESS";
export const SINGLE_ADMINS_FAIL = "SINGLE_ADMINS_FAIL";

export const CREATE_ADMINS_REQUEST = "CREATE_ADMINS_REQUEST";
export const CREATE_ADMINS_SUCCESS = "CREATE_ADMINS_SUCCESS";
export const CREATE_ADMINS_RESET = "CREATE_ADMINS_RESET";
export const CREATE_ADMINS_FAIL = "CREATE_ADMINS_FAIL";

export const UPDATE_ADMINS_REQUEST = "UPDATE_ADMINS_REQUEST";
export const UPDATE_ADMINS_SUCCESS = "UPDATE_ADMINS_SUCCESS";
export const UPDATE_ADMINS_RESET = "UPDATE_ADMINS_RESET";
export const UPDATE_ADMINS_FAIL = "UPDATE_ADMINS_FAIL";

export const DELETE_ADMINS_REQUEST = "DELETE_ADMINS_REQUEST";
export const DELETE_ADMINS_SUCCESS = "DELETE_ADMINS_SUCCESS";
export const DELETE_ADMINS_RESET = "DELETE_ADMINS_RESET";
export const DELETE_ADMINS_FAIL = "DELETE_ADMINS_FAIL";



export const CLEAR_ERRORS = "CLEAR_ERRORS";
