export const CLIENT_REQUEST = "CLIENT_REQUEST";
export const CLIENT_SUCCESS = "CLIENT_SUCCESS";
export const CLIENT_FAIL = "CLIENT_FAIL";

export const CUSTOMER_REQUEST = "CUSTOMER_REQUEST";
export const CUSTOMER_SUCCESS = "CUSTOMER_SUCCESS";
export const CUSTOMER_FAIL = "CUSTOMER_FAIL";

export const SINGLE_CLIENT_REQUEST = "SINGLE_CLIENT_REQUEST";
export const SINGLE_CLIENT_SUCCESS = "SINGLE_CLIENT_SUCCESS";
export const SINGLE_CLIENT_FAIL = "SINGLE_CLIENT_FAIL";

export const CREATE_CLIENT_REQUEST = "CREATE_CLIENT_REQUEST";
export const CREATE_CLIENT_SUCCESS = "CREATE_CLIENT_SUCCESS";
export const CREATE_CLIENT_RESET = "CREATE_CLIENT_RESET";
export const CREATE_CLIENT_FAIL = "CREATE_CLIENT_FAIL";

export const UPDATE_CLIENT_REQUEST = "UPDATE_CLIENT_REQUEST";
export const UPDATE_CLIENT_SUCCESS = "UPDATE_CLIENT_SUCCESS";
export const UPDATE_CLIENT_RESET = "UPDATE_CLIENT_RESET";
export const UPDATE_CLIENT_FAIL = "UPDATE_CLIENT_FAIL";

export const DELETE_CLIENT_REQUEST = "DELETE_CLIENT_REQUEST";
export const DELETE_CLIENT_SUCCESS = "DELETE_CLIENT_SUCCESS";
export const DELETE_CLIENT_RESET = "DELETE_CLIENT_RESET";
export const DELETE_CLIENT_FAIL = "DELETE_CLIENT_FAIL";



export const CLEAR_ERRORS = "CLEAR_ERRORS";
