export const INVOICE_REQUEST = "INVOICE_REQUEST";
export const INVOICE_SUCCESS = "INVOICE_SUCCESS";
export const INVOICE_FAIL = "INVOICE_FAIL";

export const SINGLE_INVOICE_REQUEST = "SINGLE_INVOICE_REQUEST";
export const SINGLE_INVOICE_SUCCESS = "SINGLE_INVOICE_SUCCESS";
export const SINGLE_INVOICE_FAIL = "SINGLE_INVOICE_FAIL";

export const CREATE_INVOICE_REQUEST = "CREATE_INVOICE_REQUEST";
export const CREATE_INVOICE_SUCCESS = "CREATE_INVOICE_SUCCESS";
export const CREATE_INVOICE_RESET = "CREATE_INVOICE_RESET";
export const CREATE_INVOICE_FAIL = "CREATE_INVOICE_FAIL";

export const UPDATE_INVOICE_REQUEST = "UPDATE_INVOICE_REQUEST";
export const UPDATE_INVOICE_SUCCESS = "UPDATE_INVOICE_SUCCESS";
export const UPDATE_INVOICE_RESET = "UPDATE_INVOICE_RESET";
export const UPDATE_INVOICE_FAIL = "UPDATE_INVOICE_FAIL";

export const DELETE_INVOICE_REQUEST = "DELETE_INVOICE_REQUEST";
export const DELETE_INVOICE_SUCCESS = "DELETE_INVOICE_SUCCESS";
export const DELETE_INVOICE_RESET = "DELETE_INVOICE_RESET";
export const DELETE_INVOICE_FAIL = "DELETE_INVOICE_FAIL";



export const CLEAR_ERRORS = "CLEAR_ERRORS";
