export const MENU_REQUEST = "MENU_REQUEST";
export const MENU_SUCCESS = "MENU_SUCCESS";
export const MENU_FAIL = "MENU_FAIL";

export const SINGLE_MENU_REQUEST = "SINGLE_MENU_REQUEST";
export const SINGLE_MENU_SUCCESS = "SINGLE_MENU_SUCCESS";
export const SINGLE_MENU_FAIL = "SINGLE_MENU_FAIL";

export const CREATE_MENU_REQUEST = "CREATE_MENU_REQUEST";
export const CREATE_MENU_SUCCESS = "CREATE_MENU_SUCCESS";
export const CREATE_MENU_RESET = "CREATE_MENU_RESET";
export const CREATE_MENU_FAIL = "CREATE_MENU_FAIL";

export const UPDATE_MENU_REQUEST = "UPDATE_MENU_REQUEST";
export const UPDATE_MENU_SUCCESS = "UPDATE_MENU_SUCCESS";
export const UPDATE_MENU_RESET = "UPDATE_MENU_RESET";
export const UPDATE_MENU_FAIL = "UPDATE_MENU_FAIL";

export const DELETE_MENU_REQUEST = "DELETE_MENU_REQUEST";
export const DELETE_MENU_SUCCESS = "DELETE_MENU_SUCCESS";
export const DELETE_MENU_RESET = "DELETE_MENU_RESET";
export const DELETE_MENU_FAIL = "DELETE_MENU_FAIL";



export const CLEAR_ERRORS = "CLEAR_ERRORS";
