export const POPUP_MESSAGE_REQUEST = "POPUP_MESSAGE_REQUEST";
export const POPUP_MESSAGE_SUCCESS = "POPUP_MESSAGE_SUCCESS";
export const POPUP_MESSAGE_FAIL = "POPUP_MESSAGE_FAIL";

export const SINGLE_POPUP_MESSAGE_REQUEST = "SINGLE_POPUP_MESSAGE_REQUEST";
export const SINGLE_POPUP_MESSAGE_SUCCESS = "SINGLE_POPUP_MESSAGE_SUCCESS";
export const SINGLE_POPUP_MESSAGE_FAIL = "SINGLE_POPUP_MESSAGE_FAIL";

export const CREATE_POPUP_MESSAGE_REQUEST = "CREATE_POPUP_MESSAGE_REQUEST";
export const CREATE_POPUP_MESSAGE_SUCCESS = "CREATE_POPUP_MESSAGE_SUCCESS";
export const CREATE_POPUP_MESSAGE_RESET = "CREATE_POPUP_MESSAGE_RESET";
export const CREATE_POPUP_MESSAGE_FAIL = "CREATE_POPUP_MESSAGE_FAIL";

export const UPDATE_POPUP_MESSAGE_REQUEST = "UPDATE_POPUP_MESSAGE_REQUEST";
export const UPDATE_POPUP_MESSAGE_SUCCESS = "UPDATE_POPUP_MESSAGE_SUCCESS";
export const UPDATE_POPUP_MESSAGE_RESET = "UPDATE_POPUP_MESSAGE_RESET";
export const UPDATE_POPUP_MESSAGE_FAIL = "UPDATE_POPUP_MESSAGE_FAIL";

export const DELETE_POPUP_MESSAGE_REQUEST = "DELETE_POPUP_MESSAGE_REQUEST";
export const DELETE_POPUP_MESSAGE_SUCCESS = "DELETE_POPUP_MESSAGE_SUCCESS";
export const DELETE_POPUP_MESSAGE_RESET = "DELETE_POPUP_MESSAGE_RESET";
export const DELETE_POPUP_MESSAGE_FAIL = "DELETE_POPUP_MESSAGE_FAIL";



export const CLEAR_ERRORS = "CLEAR_ERRORS";
