export const SUBSCRIPTION_CANCELLATION_REQUEST = "SUBSCRIPTION_CANCELLATION_REQUEST";
export const SUBSCRIPTION_CANCELLATION_SUCCESS = "SUBSCRIPTION_CANCELLATION_SUCCESS";
export const SUBSCRIPTION_CANCELLATION_FAIL = "SUBSCRIPTION_CANCELLATION_FAIL";

export const SINGLE_SUBSCRIPTION_CANCELLATION_REQUEST = "SINGLE_SUBSCRIPTION_CANCELLATION_REQUEST";
export const SINGLE_SUBSCRIPTION_CANCELLATION_SUCCESS = "SINGLE_SUBSCRIPTION_CANCELLATION_SUCCESS";
export const SINGLE_SUBSCRIPTION_CANCELLATION_FAIL = "SINGLE_SUBSCRIPTION_CANCELLATION_FAIL";

export const CREATE_SUBSCRIPTION_CANCELLATION_REQUEST = "CREATE_SUBSCRIPTION_CANCELLATION_REQUEST";
export const CREATE_SUBSCRIPTION_CANCELLATION_SUCCESS = "CREATE_SUBSCRIPTION_CANCELLATION_SUCCESS";
export const CREATE_SUBSCRIPTION_CANCELLATION_RESET = "CREATE_SUBSCRIPTION_CANCELLATION_RESET";
export const CREATE_SUBSCRIPTION_CANCELLATION_FAIL = "CREATE_SUBSCRIPTION_CANCELLATION_FAIL";

export const UPDATE_SUBSCRIPTION_CANCELLATION_REQUEST = "UPDATE_SUBSCRIPTION_CANCELLATION_REQUEST";
export const UPDATE_SUBSCRIPTION_CANCELLATION_SUCCESS = "UPDATE_SUBSCRIPTION_CANCELLATION_SUCCESS";
export const UPDATE_SUBSCRIPTION_CANCELLATION_RESET = "UPDATE_SUBSCRIPTION_CANCELLATION_RESET";
export const UPDATE_SUBSCRIPTION_CANCELLATION_FAIL = "UPDATE_SUBSCRIPTION_CANCELLATION_FAIL";

export const DELETE_SUBSCRIPTION_CANCELLATION_REQUEST = "DELETE_SUBSCRIPTION_CANCELLATION_REQUEST";
export const DELETE_SUBSCRIPTION_CANCELLATION_SUCCESS = "DELETE_SUBSCRIPTION_CANCELLATION_SUCCESS";
export const DELETE_SUBSCRIPTION_CANCELLATION_RESET = "DELETE_SUBSCRIPTION_CANCELLATION_RESET";
export const DELETE_SUBSCRIPTION_CANCELLATION_FAIL = "DELETE_SUBSCRIPTION_CANCELLATION_FAIL";



export const CLEAR_ERRORS = "CLEAR_ERRORS";
