export const WEBSITE_PACKAGE_REQUEST = "WEBSITE_PACKAGE_REQUEST";
export const WEBSITE_PACKAGE_SUCCESS = "WEBSITE_PACKAGE_SUCCESS";
export const WEBSITE_PACKAGE_FAIL = "WEBSITE_PACKAGE_FAIL";

export const WEBSITE_SINGLE_PACKAGE_REQUEST = "WEBSITE_SINGLE_PACKAGE_REQUEST";
export const WEBSITE_SINGLE_PACKAGE_SUCCESS = "WEBSITE_SINGLE_PACKAGE_SUCCESS";
export const WEBSITE_SINGLE_PACKAGE_FAIL = "WEBSITE_SINGLE_PACKAGE_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";