export const INVOICE_REQUEST = "INVOICE_REQUEST";
export const INVOICE_SUCCESS = "INVOICE_SUCCESS";
export const INVOICE_FAIL = "INVOICE_FAIL";

export const WOOCOMMERCE_INVOICE_REQUEST = "WOOCOMMERCE_INVOICE_REQUEST";
export const WOOCOMMERCE_INVOICE_SUCCESS = "WOOCOMMERCE_INVOICE_SUCCESS";
export const WOOCOMMERCE_INVOICE_FAIL = "SINGLE_INVOICE_FAIL";

export const SINGLE_INVOICE_REQUEST = "SINGLE_INVOICE_REQUEST";
export const SINGLE_INVOICE_SUCCESS = "SINGLE_INVOICE_SUCCESS";
export const SINGLE_INVOICE_FAIL = "SINGLE_INVOICE_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
