export const SUBSCRIPTION_REQUEST = "SUBSCRIPTION_REQUEST";
export const SUBSCRIPTION_SUCCESS = "SUBSCRIPTION_SUCCESS";
export const SUBSCRIPTION_FAIL = "SUBSCRIPTION_FAIL";

export const SINGLE_SUBSCRIPTION_REQUEST = "SINGLE_SUBSCRIPTION_REQUEST";
export const SINGLE_SUBSCRIPTION_SUCCESS = "SINGLE_SUBSCRIPTION_SUCCESS";
export const SINGLE_SUBSCRIPTION_FAIL = "SINGLE_SUBSCRIPTION_FAIL";



export const CLEAR_ERRORS = "CLEAR_ERRORS";
