export const SUBSCRIPTION_REQUEST = "SUBSCRIPTION_REQUEST";
export const SUBSCRIPTION_SUCCESS = "SUBSCRIPTION_SUCCESS";
export const SUBSCRIPTION_FAIL = "SUBSCRIPTION_FAIL";

export const CUSTOMER_REQUEST = "CUSTOMER_REQUEST";
export const CUSTOMER_SUCCESS = "CUSTOMER_SUCCESS";
export const CUSTOMER_FAIL = "CUSTOMER_FAIL";

export const UPDATE_BILLING_REQUEST = "UPDATE_BILLING_REQUEST";
export const UPDATE_BILLING_SUCCESS = "UPDATE_BILLING_SUCCESS";
export const UPDATE_BILLING_FAIL = "SUBSCRIPTION_FAIL";
export const UPDATE_BILLING_RESET = "SUBSCRIPTION_FAIL";

export const SINGLE_SUBSCRIPTION_REQUEST = "SINGLE_SUBSCRIPTION_REQUEST";
export const SINGLE_SUBSCRIPTION_SUCCESS = "SINGLE_SUBSCRIPTION_SUCCESS";
export const SINGLE_SUBSCRIPTION_FAIL = "SINGLE_SUBSCRIPTION_FAIL";



export const CLEAR_ERRORS = "CLEAR_ERRORS";
