export const SUPPORT_REQUEST = "SUPPORT_REQUEST";
export const SUPPORT_SUCCESS = "SUPPORT_SUCCESS";
export const SUPPORT_FAIL = "SUPPORT_FAIL";

export const SINGLE_SUPPORT_REQUEST = "SINGLE_SUPPORT_REQUEST";
export const SINGLE_SUPPORT_SUCCESS = "SINGLE_SUPPORT_SUCCESS";
export const SINGLE_SUPPORT_FAIL = "SINGLE_SUPPORT_FAIL";

export const SUPPORT_CHAT_REQUEST = "SUPPORT_CHAT_REQUEST";
export const SUPPORT_CHAT_SUCCESS = "SUPPORT_CHAT_SUCCESS";
export const SUPPORT_CHAT_RESET = "SUPPORT_CHAT_RESET";
export const SUPPORT_CHAT_FAIL = "SUPPORT_CHAT_FAIL";

export const CREATE_SUPPORT_REQUEST = "CREATE_SUPPORT_REQUEST";
export const CREATE_SUPPORT_SUCCESS = "CREATE_SUPPORT_SUCCESS";
export const CREATE_SUPPORT_RESET = "CREATE_SUPPORT_RESET";
export const CREATE_SUPPORT_FAIL = "CREATE_SUPPORT_FAIL";

export const UPDATE_SUPPORT_REQUEST = "UPDATE_SUPPORT_REQUEST";
export const UPDATE_SUPPORT_SUCCESS = "UPDATE_SUPPORT_SUCCESS";
export const UPDATE_SUPPORT_RESET = "UPDATE_SUPPORT_RESET";
export const UPDATE_SUPPORT_FAIL = "UPDATE_SUPPORT_FAIL";

export const DELETE_SUPPORT_REQUEST = "DELETE_SUPPORT_REQUEST";
export const DELETE_SUPPORT_SUCCESS = "DELETE_SUPPORT_SUCCESS";
export const DELETE_SUPPORT_RESET = "DELETE_SUPPORT_RESET";
export const DELETE_SUPPORT_FAIL = "DELETE_SUPPORT_FAIL";



export const CLEAR_ERRORS = "CLEAR_ERRORS";
